create header
jho378/airbnb-clone-coding pull request #3
Opened 2022-04-06 04:42 UTC by jeongwoo-hong

header

2022-04-06 13:48 UTC, jho378 approved these changes
완전 고생 많아따... 자료구조 화이팅! . !

2022-04-08 11:18 UTC, sewonK requested changes
전체적으로 깔끔히 잘 짠 것 같아~~ 내 코멘트 보면서 수정사항 반영해서 다시 풀리퀘 보내면 좋을듯!!! 👍

2022-04-08 11:18 UTC, sewonK commented on index.html
> +            <span id="covid"><u>에어비앤비의 코로나19 대응 방안에 대한 최신 정보를 확인하세요.</u></span>
`<u>` 태그는 HTML 4 버전에서는 밑줄 긋기 기능으로 사용했었는데, 밑줄 기능을 css가 지원하면서 html에서 `<u>`태그는 철자 오류나 주석 표시만을 위해 사용한다고 해~~ CSS에 `text-decoration: underline;`을 주면 밑줄 그어지거든?! 바꿔보는건 어떨까용!? https://webzz.tistory.com/348 참고 링크입니당

2022-04-08 11:18 UTC, sewonK commented on index.html
> +                    <input placeholder="어디로 여행가세요?">
오~~ placeholder 굿굿!!👍 근데 실제로 입력하면 폰트가 흰색이라 입력 값이 안보인다 ㅋㅋ css에서 color를 black으로 바꿔줘~~~

2022-04-08 11:18 UTC, sewonK commented on index.html
> +</html>
github에서 보면 여기에 - 표시로 No newline at end of file이라는 게 뜨거든?! 한 파일에서 맨 마지막 줄의 경우는 개행하는 컨벤션을 따르고 있다고 해! 지금 코딩하는데는 큰 영향은 없지만 알아두면 좋을 것 같아서! https://minz.dev/19 이유가 궁금하면 여기 참고해도 좋을 듯 ㅎㅎㅎ

2022-04-08 11:18 UTC, sewonK commented on style.css
> +}
여기도 마찬가지! 한칸 개행하기~

2022-04-08 11:18 UTC, sewonK commented on style.css
> +    background-color: black;
모든 항목의 background-color를 black으로 주면 header의 경우 잘 처리되겠지만, main이나 footer가 스타일이 달라지게될거야ㅠ conflict 해결하면서 아마 이 부분을 바꿔줘야할건데 전체 background color를 건드리지 않고 div별로 background 컬러를 넣어주는게 코드 합치기엔 편할듯!!

2022-04-08 11:18 UTC, sewonK commented on style.css
> +
.location, .location p
.checkin, .checkin p
.checkout, checkout p
.num_person, .num_person p
여기 style을 설정하는 부분이 중복됐지?!! 코드 중복은 못참지,,,, css의 하위 선택자와 자식 선택자에 대해서 공부해보면 중복을 줄일 수 있을 것 같아~~ 예를 들어 나라면 div로 location, checkin, checkout, num_person 를 하나로 묶어서 search-button과 분리시킨 뒤에 한방에 스타일을 먹일 것 같음!
```css
.[새로 만든 div] div {
    background-color: white;
    width: 100px;
    height: 50px;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
}

.[새로 만든 div] p {
    background-color: white;
    color: black;
    width: 100px;
    height: 20px;
    margin: 0px;
    font-size: 15px;
    display: flex;
    flex-direction: column;
    justify-content: flex-end;
}
```
이런식으루 ?!! 하위선택자랑 자식선택자는 https://rgy0409.tistory.com/138 요기서 더 참고 가능~~~

2022-04-09 08:23 UTC, juyeon0 commented
ㅎㅎ 수고 많았어! 23일에 만나요~~

2022-04-11 12:47 UTC, closed without merging